### PR TITLE
[compatibility] windows: __typeof__ macro is not available in MSVC

### PR DESCRIPTION
**Pull request by iiSeymour**

### CODE REVIEW

**Comment by lh3** [comment]
I wouldn't change an existing API even if it is mostly private. This will fail other kalloc uses. Please use the following APIs instead:

https://github.com/lh3/minigraph/blob/3398263be225ba923140a1081b505b71f2cdf8fb/kalloc.h#L30-L32

**Comment by lh3** [comment]
I have updated kalloc.* to a more recent version that has the following macros:

https://github.com/lh3/minimap2/blob/c3d461e22a381548e7bb2090b3f650de904bb137/kalloc.h#L30-L32

If you replace all KMALLOC() instances with Kmalloc(), I will be happy to accept a PR. Thanks.

**Comment by lh3** [comment]
BTW, I am also thinking to cut a release in the next few days.

**Comment by iiSeymour** [comment]
Great, thanks @lh3 I have submitted https://github.com/lh3/minimap2/pull/1051.

**Pull request closed without merging**
