### PR TITLE
update url to github

### PR DESCRIPTION
**Pull request by skoren**
On our system I also had to change from -march=native to -march=core-avx2 -mno-avx -mno-bmi2 but I think this is due to an older ld version.

### CODE REVIEW

**Comment by lh3** [comment]
Thanks! I have fixed URL via b4edb0c. I am hesitant to change -march because "core-avx2" would require AVX2. I am using "native" because minimap2 will run faster with SSE4.1, but without any `-march` options, gcc only emits SSE2 code. I will leave this issue open to see if others have better solutions.

**Comment by lh3** [comment]
PS: Another possibility is to use `-msse4` without `-march=native`, but users on older CPUs without SSE4 have to manually comment out `-msse4` in Makefile. There are also more advanced techniques like CPU dispatching, but that is overkilling.

**Comment by skoren** [comment]
Perhaps there is a way to check what a cpu supports? Something like:
```
gcc -march=native -Q --help=target | grep march
```
on our system reports core-avx2 and corei7 on an older machine.

**Comment by lh3** [comment]
@skoren I have pushed a new change that use `-msse4` by default and disable it if you use `make sse2only=1`. Could you try if that works? Thanks.

**Comment by skoren** [comment]
Yes, both those options work, thanks.

**Comment by skoren** [comment]
Yes, both those options work, thanks.

**Comment by lh3** [comment]
Interestingly,
```sh
gcc -march=native -Q --help=target | grep march
```
gives `core2` on my machine. `core2` doesn't have SSE4 support (not `__SSE4_1__` macro). However, if I compile with `-march=native`, the `__SSE4_1__` macro will become defined.

Anyway, I will close this issue for now. Thanks for the report. It is always interesting to see how machines behave differently.

**Pull request closed without merging**
