### PR TITLE
Add linux gcc-8 test case on Travis CI.

### PR DESCRIPTION
**Pull request by junaruga**
This fixes https://github.com/lh3/minimap2/issues/234 .

### CODE REVIEW

**Comment by lh3** [comment]
Thanks, but I don't see this necessary.

**Comment by junaruga** [comment]
@lh3 oh why you do not need it?

**Comment by lh3** [comment]
1. Their upgrading to gcc 7 has nothing to do with this repo.

2. I don't want new compiler features. I want to minimize compiler-specific features.

This PR is not happening.

**Comment by junaruga** [comment]
@lh3 Alright. I respect your thoughts.  It sounds like that `minimap2` likes minimalism. 👌

**Comment by lh3** [comment]
Thanks for the understanding.

**Pull request closed without merging**
