### PR TITLE
Added a "lastz"-like CIGAR format.

### PR DESCRIPTION
**Pull request by lucventurini**
I added a "--lastz" switch for the command line interface, which produces an output following the format of LASTZ "--format=cigar" option, see here: http://www.bx.psu.edu/miller_lab/dist/README.lastz-1.02.00/README.lastz-1.02.00a.html#fmt_cigar.

This should allow minimap2 to be compatible with Cactus.

### CODE REVIEW

**Comment by lh3** [comment]
Thanks for the offer. However, I prefer to keep the core implementation small. I am usually reluctant to add features just for a particular program.

How about this: the latest master implements a PAF to LASTZ-cigar converter. You can run minimap2 with
```sh
minimap2 -c ref.fa query.fa | k8 misc/paf2aln.js -f lastz-cigar - >  out.cigar
```
to get LASTZ-cigar output. Here, `k8` is available from the [binary release](https://github.com/lh3/minimap2/releases) (in minimap2-2.5_x64-linux/misc). You can also convert PAF to MAF with
```sh
minimap2 --cs=long ref.fa query.fa | k8 misc/paf2aln.js -f maf - >  out.maf
```
or BLAST-like output with `-f aln`. More output formats may be added in future.

**Comment by lucventurini** [comment]
Thank you for taking the time to implement this in paf2aln.js; it functions very well.
I do find, however, the javascript utilities a bit impractical, especially in pipelines. I might write some wrappers that can be executed directly and make a second pull request, if that is OK with you.

I would also like to say that minimap2 is impressive - I have been able to perform alignments that would have taken days, in minutes. Hence my interest in integrating it in Cactus!

**Comment by lh3** [comment]
> I do find, however, the javascript utilities a bit impractical, especially in pipelines. I might write some wrappers that can be executed directly and make a second pull request

Could you elaborate on the problem with pipelining? What kind of wrapper are you thinking to implement? Thank you.

> I have been able to perform alignments that would have taken days, in minutes.

Just note that minimap2 is only good for sequence identity up to 20% or so. LASTZ is more sensitive to divergent species pairs.

**Comment by lucventurini** [comment]
>>   I do find, however, the javascript utilities a bit impractical, especially in pipelines. I might write some wrappers that can be executed directly and make a second pull request
> Could you elaborate on the problem with pipelining? What kind of wrapper are you thinking to implement? Thank you.

For general purpose pipelines, such as Cactus, I find it is best practice to have a command rather than having to specify the location of a script to be launched, as it is potentially less brittle. As for wrappers, I am thinking of simple bash executables to be installed alongside minimap2 in PATH (together with the misc/ folder).

**Comment by lucventurini** [comment]
> Just note that minimap2 is only good for sequence identity up to 20% or so. LASTZ is more sensitive to divergent species pairs.

I will keep that in mind! My primary research purpose is to compare ecotypes of the same species, though, so this limitation should not cause many relevant problems.

**Pull request closed without merging**
