### PR TITLE
Improved mapping results for a multi-part index - merging

### PR DESCRIPTION
**Pull request by hasindu2008**
The following features were added (for uni-segment reads only). The additions were done such that minimal changes are done on existing code. 

1. --multi-prefix option to specify a temporary file prefix
2. Dumping the internal state of each mapping to temporary files
3. Merging the intermediate values to generate the final output (merged headers, fixed mapq, fixed flags and the printing of the correct number of the secondary mappings/unaligned reads)

Tested using two datasets 33k reads and 3.9M synthetic long reads. Tested to confirm that the changes do not affect the existing result (see the attached evaluate_accuracy.zip)

[evaluate_accuracy.zip](https://github.com/lh3/minimap2/files/2126327/evaluate_accuracy.zip)

### CODE REVIEW

**Comment by lh3** [comment]
Thanks so much for this. I will review and merge later, definitely getting this ready for the next release 2.12.

**Comment by lh3** [comment]
Learning from your code, I have reimplemented the support of multi-part index at the [split branch](https://github.com/lh3/minimap2/tree/split). The new option is `--split-prefix`, which has the same behavior as your `--multi-prefix`. If you have time, you may test it. I will merge this branch to "master" once I confirm it is stable.

**Comment by lh3** [comment]
I have merged the split branch to master. I will close this PR. If you find bugs in the new feature, please create an issue. Thank you very much for this PR. It has been very helpful.

**Comment by jianshu93** [comment]
Dear all,

Just curious whether this idea will affect many reference genomes that are closely related to each other, for example there are 5000 bacterial genomes, and some are closely related strains, half of the strains were in the first part , but other strains were in a second part. The accuracy testings are based on a single human genome, in cases where many similar genomes were in the database, will this idea still work?

Thanks,
Jianshu

**Pull request closed without merging**
